# CHATBOT

#Car price prediction model ML

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
#Read CSV File
cars_df = pd.read_csv("Resources/cars_info.csv")
cars_df.head()

,ID,Name,Price,Brand,Model,Variant,Series,Year,Kilometers,Type,Gearbox,Fuel,Status,CC,Color,Seating Capacity
0,11530130,2010 Toyota Rukus Build 2 AZE151R,9999,Toyota,Rukus,Build 2,AZE151R,2010,263000,Wagon,Automatic,Unleaded Petrol,Used,2362,Grey,5
1,12190570,2021 Mercedes-Benz V 250 D Avantgarde MWB 447 ...,117990,Mercedes-Benz,V,250 D Avantgarde MWB,447 MY21,2021,19,Wagon,Automatic,Diesel,New In Stock,2143,Black,7
2,12321855,2021 Mercedes-Benz Valente 116 CDI MWB RWD 447...,79990,Mercedes-Benz,Valente,116 CDI MWB RWD,447 MY21,2021,24,Wagon,Automatic,Diesel,New In Stock,2143,Black,8
3,12346971,2010 Mercedes-Benz E250 CDI Avantgarde 207,34990,Mercedes-Benz,E250,CDI Avantgarde,207,2010,120579,Cabriolet,Automatic,Diesel,Used,2143,Black,4
4,12363884,2016 Holden Cruze CD JH MY16,15990,Holden,Cruze,CD,JH MY16,2016,72506,Sportswagon,Automatic,Unleaded Petrol,Used,1796,White,5

In [3]:
cars_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17048 entries, 0 to 17047
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                17048 non-null  int64
 1   Name              17048 non-null  object
 2   Price             17048 non-null  int64
 3   Brand             17048 non-null  object
 4   Model             17048 non-null  object
 5   Variant           17048 non-null  object
 6   Series            17048 non-null  object
 7   Year              17048 non-null  int64
 8   Kilometers        17048 non-null  int64
 9   Type              17048 non-null  object
 10  Gearbox           17048 non-null  object
 11  Fuel              17048 non-null  object
 12  Status            17048 non-null  object
 13  CC                17048 non-null  int64
 14  Color             17048 non-null  object
 15  Seating Capacity  17048 non-null  int64
dtypes: int64(6), object(10)
memory usage: 2.1+ MB

In [4]:
#Duplicate values
duplicate = cars_df.duplicated().sum()
print(f'number of duplicate rows are {duplicate}')

number of duplicate rows are 0

In [5]:
#Data Analysis
for col in cars_df.columns:
    print('Unique values of' + col)
    print(cars_df[col].unique())
    print("--------------------------------------------")

Unique values ofID
[11530130 12190570 12321855 ... 12852462 12852463 12852464]
--------------------------------------------
Unique values ofName
['2010 Toyota Rukus Build 2 AZE151R'
 '2021 Mercedes-Benz V 250 D Avantgarde MWB 447 MY21'
 '2021 Mercedes-Benz Valente 116 CDI MWB RWD 447 MY21' ...
 '2015 Land Rover Discovery 4 3.0 SDV6 HSE MY15'
 '2002 Holden Jackaroo SE LWB (4X4) U8'
 '2005 Toyota RAV4 Cruiser (4X4) ACA23R']
--------------------------------------------
Unique values ofPrice
[  9999 117990  79990 ...  31962  26992  35992]
--------------------------------------------
Unique values ofBrand
['Toyota' 'Mercedes-Benz' 'Holden' 'Nissan' 'Ford' 'BMW' 'Isuzu' 'Hyundai'
 'Volkswagen' 'Lexus' 'Mazda' 'Audi' 'Subaru' 'Mitsubishi' 'Kia' 'Skoda'
 'Renault' 'Porsche' 'Jeep' 'Honda' 'Ssangyong' 'Volvo' 'Land Rover' 'MG'
 'Suzuki' 'Ram' 'Mini' 'Jaguar' 'LDV' 'HSV' 'Alfa Romeo' 'Aston Martin'
 'Hino' 'Chrysler' 'Citroen' 'Infiniti' 'Peugeot' 'Chevrolet'
 'Lamborghini' 'Fiat' 'Bentley' 'Dodge' 'Haval' 'Great Wall' 'Abarth'
 'Foton' 'Genesis' 'GWM' 'FPV' 'Mitsubishi Fuso' 'Maserati' 'Iveco'
 'Mahindra' 'Opel' 'Saab' 'Chery' 'Smart' 'Proton' 'Cupra']
--------------------------------------------
Unique values ofModel
['Rukus' 'V' 'Valente' 'E250' 'Cruze' 'X-Trail' 'Territory' '325I'
 'Statesman' 'Commodore' 'D-MAX' 'Focus' 'Elantra' 'Santa FE' 'I30'
 'Caddy' 'Tucson' 'RX350' 'Falcon' 'Vito' '2' 'Q3' 'Forester' 'Patrol'
 'RAV4' 'Landcruiser Prado' 'Sprinter' 'Triton' 'Landcruiser' 'Ranger'
 'Colorado' 'Outlander' 'Sportage' 'Kluger' 'Octavia' 'Pajero Sport'
 '430I' 'Golf' 'Clio' 'Navara' 'Q5' 'Cayenne' 'Landcruiser 70 Series'
 'Hilux' 'Corolla' 'Pajero' 'CX-8' 'Wrangler' 'Carnival' 'Trailblazer'
 'Boxster' 'Multivan' 'Transit Custom' 'Civic' 'Grand Carnival' 'Everest'
 'Aurion' 'Stavic' 'S7' 'MU-X' 'Tiguan' '220D' 'X3' 'Rodeo' '320I' 'XC40'
 'CX-9' 'I45' 'Viano' 'Calais' 'Grand Cherokee' 'Discovery 4' 'Lancer'
 'Compass' 'CX-5' 'Amarok' 'Q2' 'GLA45' 'HS' 'Discovery Sport' 'Vitara'
 '3' 'Koleos' 'BT-50' 'A4' 'X6' 'ASX' 'Swift' 'Eclipse Cross' 'Defender'
 '1500' 'Sorento' 'HR-V' 'Arteon' 'Astra' 'Iload' 'Yaris' 'Courier'
 'Camry' 'Patriot' '3D Hatch' 'A250' 'Puma' 'Accent' 'S60' 'Dualis' 'E350'
 'Pathfinder' 'Trax' 'CR-V' 'Pulsar' 'Range Rover Sport' 'A3' 'LS500'
 'Range Rover Evoque' 'Fiesta' 'Grand Vitara' 'XK' 'F-Pace' 'Liberty'
 'C200' 'X5' 'IS250' 'X350' 'T60' 'Rondo' 'Range Rover' 'Impreza' '6'
 'Cherokee' 'Hiace' 'CLA45' 'Kamiq' 'Wrangler Unlimited' 'Veloster'
 'Malibu' 'C250' 'Stinger' 'Monaro' '125I' 'Mustang' 'Cerato' 'CX-3'
 'Imax' 'Kona' 'UTE' 'Clubsport' 'Mondeo' 'Caprice' 'A6' 'Giulia' 'Polo'
 'C-HR' 'Touareg' 'Qashqai' 'SQ5' 'Outback' 'IS350' 'Barina Spark' 'XV'
 'XC90' 'M340I' 'Captiva' 'A5' 'Barina' '328I' 'Passat' 'Q7' 'RS Q3'
 '535D' 'G10+' 'RC350' 'T-Cross' 'Rapide' 'A45' 'V40' 'X1' 'Macan'
 'Odyssey' 'IX35' 'Maloo' 'Accord Euro' 'Equinox' 'Escape' 'GLE300'
 'RX350L' 'Jazz' 'Maxima' '300' 'Crewman' 'PT Cruiser' 'Soul' '118I'
 'Levorg' 'F-Type' 'NX200T' 'Gladiator' 'GS350' 'XC60' 'A7' 'E63'
 'C5 Aircross' 'NX300' 'X4' 'Sonata' 'Transporter' 'Tiida' 'Megane'
 'Arkana' '220I' '330I' 'C63' 'WRX' 'Karoq' 'S3' 'Fortuner' 'Tarago'
 'Acadia' 'Q30' 'Express' 'Captur' '2008' 'Beetle' 'GLE250' 'GLS350'
 'Endura' 'Colorado 7' 'Superb' 'GLC63' 'X2' 'M2' 'B200' '86' 'S5' 'Z4'
 'C30' 'X7' 'Scala' 'RIO' 'Cooper' 'Yaris Cross' 'Discovery 3' 'Murano'
 'Q50' 'CLK320' 'Rexton' 'GLC' 'Partner' 'Accord' 'Silverado' 'S4' '370Z'
 'TT' 'E-Pace' 'A180' 'Challenger' 'RX450H' 'UX200' 'GLA250' 'MG3 Auto'
 '207' '380' 'Getz' 'A35' 'Freelander 2' 'Countryman' 'CLA250' 'GLE350'
 'Fairlane' 'Micra' '440I' 'IS250C' 'GLE43' 'GLC43' 'GLC250' 'GLE63'
 'Kodiaq' 'Range Rover Velar' 'Cayman' 'Ecosport' '428I' 'Discovery'
 'V250' 'Scirocco' 'CLK350' '3008' 'Optima' 'Urus' 'A1' 'Freemont' 'RS3'
 'Berlingo' 'Clubman' 'Adventra' 'XF' 'SLK55' 'G10' '318D' 'Juke' 'Staria'
 'Palisade' 'Seltos' 'CX-30' 'C180' 'Kuga' 'Picanto' 'GR Yaris'
 'Starwagon' 'Yeti' 'ML350' 'M3' 'Caravelle' 'Continental' 'Nitro' 'H2'
 'Q8' 'Jetta' 'HiAce' 'R8' 'RX300' '308' 'MX-30' 'V240' 'Trafic' 'IS200T'
 '595' 'Tunland' 'Allroad Quattro' 'CLK200' 'Prius' 'G70' 'Coupe' 'GLC350'
 'GL350' 'Transit' 'Festiva' 'Epica' 'X240' 'Ignis' 'GLA35' "Pro_cee'd"
 'DS3' 'H9' 'Steed' 'Avensis' 'C220' 'Journey' 'GLS63' 'Haval H6' 'Baleno'
 'H6' '128TI' 'CX-7' 'ML400' 'NX300H' 'Cabrio' 'S63' 'Laguna' 'M8' 'I40'
 'S350' 'Prius-C' 'GT' 'ML300' 'V60' 'I20' 'GLB35' 'RS 3' 'ML500' 'M135I'
 'Avalon' 'BRZ' 'A140' 'LC500H' 'D90' 'S-Cross' 'Grand Voyager' 'F6'
 'GLS500' 'E400' 'GLE' '911' '340I' 'X250' 'GLE400' 'Santa Fe' 'Korando'
 'E55' 'Kizashi' 'Expert' '124' '540I' 'SLK250' 'Capri' 'SLK230' 'Fabia'
 '130I' 'IS300' 'RX270' 'T-ROC' 'CLA200' 'Altima' 'S1' 'GLC200' 'C6'
 '320D' 'Genesis' 'ML320' 'CLK500' 'RS5' 'M4' 'GS450H' 'RX330' 'E450'
 '318I' 'Venue' '500' '4' 'GLA200' 'Mirage' 'City' 'Integra' '300C'
 'Laser' 'Convertible' 'CLA' 'Canter' '640I' 'NX350' 'Renegade' 'V80'
 'GLB' 'Fairmont' 'IS200' 'MX-5' '420I' 'S Type' 'CT200H' 'Master'
 'Granvia' 'F250' 'HS +EV' 'CLA35' 'GL450' 'Magna' 'RX450HL' 'DB11'
 'Kangoo' 'GLC220' 'RS 6' 'RS Q8' 'RS 5' 'V200' 'B2500' 'Giulietta' 'ZS'
 'Panamera' 'ML63' 'Tribute' 'Ducato' 'C300' 'S6' 'S40' 'SL350' 'GLA'
 'ML250' 'Tribeca' 'E230' 'B180' 'Ghibli' '225I' '135I' 'CLC200' 'XE'
 'GL320' '508' '120I' 'RS4' 'C240' 'Daily' '530E' 'ES250' 'Grange'
 'Haval Jolion' 'AMG GT' 'CC' '520D' 'GLC300' 'Rapid Spaceback' 'E280'
 'Telstar' 'ZST' 'Prius C' 'Caliber' 'XUV500' 'Stonic' 'CLS250' 'Musso'
 'C5' 'Supra' 'ES350' 'A200' 'Senator' 'GLS' 'SX4' 'Camaro' 'Levante'
 'EOS' 'G63' 'Jimny' 'Paceman' 'Vienta' 'Jackaroo' 'SL55' 'X200' 'Niro'
 'GS300' 'CLK280' 'RX400H' 'IS300H' 'Quattroporte' 'Starlet' 'ES300H'
 'Alto' '208' 'M235I' '5008' 'XKR' '9-3' 'Scudo' 'Dyna' 'CLK240' '520I'
 '530D' 'XC70' '218D' 'Actyon Sports' 'Bentayga' 'GS200T' '159' 'C4'
 'Voyager' '230I' 'Colt' 'SQ8' 'UX250H' '718' '4008' 'Musso XLV' 'SQ7'
 '218I' 'M440I' 'X Type' 'J11' 'E320' 'CLA220' 'Scenic' 'Huracan' 'SL65'
 'GLA220' 'V50' 'E220' 'MR2' 'Bora' 'Townace' 'I8' 'SV' 'California'
 'LX570' 'QX80' 'C4 Picasso' 'E500' '335I' 'NX250' 'Sebring' '8' 'G37'
 'S450' 'Granturismo' '307' 'S500' 'S90' '228I' '5D Hatch' 'Roomster'
 'Roadster' '500X' 'Vectra' '530I' 'RC200T' 'C3' '5' 'SLK200' 'S400'
 'GLE450' 'Fortwo' '118D' 'ML280' 'Exora' 'QX30' 'Formentor' 'Ateca'
 'Leon' 'GT F' 'SA220' 'Echo' 'GS430' 'Insignia' 'RS 7' '316I' 'RCZ'
 'Prius V' 'LX470' 'LX600' 'C320' 'Freelander' 'Commander' 'C350' 'CLS450'
 'Citivan' 'A160' '420D']
--------------------------------------------
Unique values ofVariant
['Build 2' '250 D Avantgarde MWB' '116 CDI MWB RWD' ... '2.0I Premium AWD'
 'Koup SI' 'D5 Inscription']
--------------------------------------------
Unique values ofSeries
['AZE151R' '447 MY21' '207' ... 'F33 MY15' '256 MY19' 'MY23']
--------------------------------------------
Unique values ofYear
[2010 2021 2016 2017 2011 2005 2003 2015 2013 2020 2009 2012 2014 2019
 2004 2018 2022 2006 2007 2008 2000 2001 2002 1996 1998 1999 1997 1995
 1991 1993 1994 1989 1992 1990]
--------------------------------------------
Unique values ofKilometers
[263000     19     24 ... 237113 238768 255809]
--------------------------------------------
Unique values ofType
['Wagon' 'Cabriolet' 'Sportswagon' 'Sedan' 'Cab Chassis' 'Hatchback' 'Van'
 'Crew Cab Van' 'Liftback' 'Double Cab Utility' 'Crew Cab Utility'
 'Double Cab Chassis' 'Crew Cab Pickup' 'Super Cab Chassis' 'Convertible'
 'Dual Cab Pick-up' 'Double Cab Pick Up' 'Softtop' 'Roadster'
 'Dual Cab Utility' 'Coupe' 'King Cab Pickup' 'Utility' 'Dual Cab Chassis'
 'Club Cab Pickup' 'Hardtop' 'Club Cab Chassis' 'Crew Cab Chassis'
 'X Cab Cab Chassis' 'Sportback' 'Fastback' 'Saloon' 'Space Cab Utility'
 'Freestyle Cab Chassis' 'Bus' 'Super Cab Utility' 'X Cab Pickup' 'Estate'
 'Panel Van' 'Blind Van' 'Space Cab Chassis' 'Club Cab Utility'
 'Leaf Cab Chassis' 'Coach' 'Crew Van' 'Troop Carrier' 'King Cab Pick Up'
 'Pickup' 'X Cab Utility' 'Space Cab Pickup' 'Freestyle Utility'
 'Super Cab Pickup' 'Coil Cab Chassis' 'Cab Chassis Tray' 'Softback'
 'King Cab Utility']
--------------------------------------------
Unique values ofGearbox
['Automatic' 'Manual' 'Front' 'AWD' 'Rear']
--------------------------------------------
Unique values ofFuel
['Unleaded Petrol' 'Diesel' 'Premium Unleaded Petrol'
 'Premium Unleaded/Electric' 'Unleaded Petrol/Electric'
 'Liquid Petroleum Gas' 'Diesel/Electric']
--------------------------------------------
Unique values ofStatus
[' Used' ' New In Stock' ' Demo']
--------------------------------------------
Unique values ofCC
[2362 2143 1796 2488 2720 2497 5665 2999 1596 3470 1591 1598 1995 3456
 3984 1498 1968 1998 4169 1987 2982 2477 4461 3198 2776 2360 1984 2442
 1618 2967 2298 4806 1798 2953 3200 2753 3778 3342 1999 3436 2694 2198
 2393 2498 2696 3993 5967 2979 1969 2359 2987 3565 5654 2993 2457 1997
 2440 1991 1490 3604 1996 1586 2487 1799 3196 4395 1372 1499 2401 2199
  898 1399 1497 3726 2606 2494 4477 3956 1395  999 1368 3498 1769 3444
 3955 5000 2755 2500 4367 1994 3239 2384 4999 4950 3346 6200 2151 1797
 2995 1197 3960 2499 1248 2998 2997 2191 2480 1339 5935 2179 1496 2356
 2231 6424 3311 2354 1299 1390 1950 5408 4009 2429 3179 3982 2773 3828
 2148 3700 1333 2268 2351 3649 1199 2188 2261 1975 3497 2400 3791 2521
 4664 2164 1396 6208 3199 2835 1560 4987 6162 3696 1595 1360 1898 3189
 1341 1759 3000 3378 3490 2996 5461 3630 3564  998 1582 4759 3996 3494
 4164 2991 2495 2972 3701 5552 2438 1495 3949 1373 2405 1668 5998 3197
 1364 1242 5204 1989 2378 1599 1461 2492 2260 1206 2389 1967 3246 2894
 1956 2986 1685 2925 2698 4663 1597 6417 1397 3165 2777 3596 2656 5439
 1198 4479 1600 2295 2672 3195 5038 4966 2981 1794 1896 1193 3194 6059
 1762 1781 2402 3907 3800 2736 3597 1332 1988 3990 2299 2496 5400 3824
 3954 2034 4799 1840 4134 2287 1948 2184 2960 3614 2387 2597 1388 3471
 1349 3275 2157 1742 2435 1328 2959 1580 1910 2460 2891  996 4398 4104
 3123 4163 4197 1795 3980 7300 5950 3301 1834 1323  875 2171 2988 3745
 2976 4200 2099 1971 3518 1587 2183 1970 5980 2324 1985 5663 4691 2349
 3600 3175 1468 1362 2237 4293 1850 3445 1462 1951 3724]
--------------------------------------------
Unique values ofColor
['Grey' 'Black' 'White' 'Blue' 'Green' 'WHITE' 'Silver' 'silver' 'Red'
 'Gold' 'Fuji' 'Metallic' 'Gun' 'Light' 'Cool' 'grey' 'BRITISH' 'Burgundy'
 'Orange' 'Other' 'Pepper' 'Titanium' 'white' 'Charcoal' 'Stromboli'
 'Mercury' 'Brown' 'Yellow' 'Leatherette' 'Graphite' 'Deep' 'Beige'
 'Artic' 'Frozen' 'Cream' 'neon' 'Pearl' 'Darkblue' 'maroon' 'charcoal'
 'Dark' 'Cirrus' 'blue' 'gray' 'green' 'Navy' 'Learher' 'black' 'Glacier'
 'Polar' 'Atomic' 'Whtie' 'Patriot' 'Lighting' 'Sting' 'TRUE' 'SILVER'
 'Alpine' 'Navarra' 'Neptune' 'Tenorite' 'Bronze' 'Slipstream' 'Horizon'
 'Platinum' 'Toy' 'Cherry' 'BLUE' 'Liquid' 'Sliver' 'While' 'Seduce'
 'BLACK' 'Autumn' 'Meteor' 'Soul' 'Whte' 'Crystal' 'vivid' 'Mountain'
 'light' 'Selenite' 'Lava' 'Harmony' 'GOLD' 'Vivid' 'Granite' 'Gecko'
 'red' 'Ceramic' 'Gray' 'Summit' 'Magnetic' 'Mojave' 'Ebony' 'Race'
 'sunset' 'Diamond' 'Aurora' 'Crème' 'Melbourne' 'Sapphire' 'Steel' 'Tan'
 'Olive' 'Glossy' 'pearl' 'Ruby' 'Panthera' 'Velvet' 'Vitamin' 'Sky'
 'beige' 'Sparkling' 'Baige' 'Moondust' 'crystal' 'corris' 'Coverline'
 'Purple' 'Maroon' 'Hornet' 'selenite' 'Daytona' 'Amber' 'WR' 'Fabric'
 'Ice' 'Bright' 'Champagne' 'Some' 'Tidal' 'Oolong' 'Aruba' 'Sunset'
 'burgundy' 'Marble' 'Matte' 'Metalic' 'ICE' 'Nebula' 'metallic' 'Orkney'
 'Caribbean' 'Magic' 'Estoril' 'Mineral' 'Magenta' 'Palladium' 'Snowflake'
 'GREY' 'Waite' 'Lunar' 'gold' 'Phantom' 'Misano' 'Reflex' 'Rhodium'
 'Pink' 'Silber' 'Fusion' 'Celestite' 'Winning' 'Edge' 'Winter' 'Oak'
 'Cosmos' 'Lightning' 'NAVY' 'Plasma' 'Flamenco' 'Mica' 'Ivory' 'impulse'
 'New' 'Aluminium' 'candy' 'Candy' 'Jungle' 'Gunmetal' 'diamond' 'British'
 'Jatoba' 'pre' 'Alabaster' 'Carbon' 'Stoff' 'gunmetal' 'Magnetite'
 'Galena' 'Dusty' 'Satin' 'Nitrate' 'Karma' 'MINERAL' 'Charcol' 'Leather'
 'Clear' 'RED' 'Marine' 'Greg' 'night' 'Starlight' 'Onyx' 'Conquer'
 'CRYSTAL' 'Splice' 'Cloth' 'Emerald' 'Bugerney' 'Heron' 'Ocean' 'Frosted'
 'Rouge' 'Surfy' 'Galapagos' 'Pacific' 'Smoke' 'Iridium' 'Off' 'Forged'
 'Alto' 'SIlver' 'Onxy' 'Petroleum' 'Car' 'Machine' 'Gloss' 'Velour'
 'yellow' 'Space' 'Missano' 'Velocity' 'Perl' 'Glazier']
--------------------------------------------
Unique values ofSeating Capacity
[ 5  7  8  4  2  3 14  6  9 11]
--------------------------------------------

In [6]:
cars_df.drop(columns=['ID','Model', 'Name'], inplace=True)
cars_df.head()

,Price,Brand,Variant,Series,Year,Kilometers,Type,Gearbox,Fuel,Status,CC,Color,Seating Capacity
0,9999,Toyota,Build 2,AZE151R,2010,263000,Wagon,Automatic,Unleaded Petrol,Used,2362,Grey,5
1,117990,Mercedes-Benz,250 D Avantgarde MWB,447 MY21,2021,19,Wagon,Automatic,Diesel,New In Stock,2143,Black,7
2,79990,Mercedes-Benz,116 CDI MWB RWD,447 MY21,2021,24,Wagon,Automatic,Diesel,New In Stock,2143,Black,8
3,34990,Mercedes-Benz,CDI Avantgarde,207,2010,120579,Cabriolet,Automatic,Diesel,Used,2143,Black,4
4,15990,Holden,CD,JH MY16,2016,72506,Sportswagon,Automatic,Unleaded Petrol,Used,1796,White,5

In [7]:

from sklearn.preprocessing import LabelEncoder, OneHotEncoder


# Load dataset (assuming `cars_df` is already loaded)
# Define Features (X) and Target (y)
X = cars_df.drop(columns=['Price'])  
y = cars_df['Price']

# Identify categorical columns
categorical_cols = ['Brand', 'Variant', 'Series', 'Year', 'Type', 'Gearbox', 'Fuel', 'Status', 'Color']

# Applied Label Encoding 
encoder = LabelEncoder()
for col in categorical_cols:
    X[col] = encoder.fit_transform(X[col])

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

print("Model training complete!")

Model training complete!

#Linear Regression

In [8]:
predict = model.predict(X_test)
predict

array([34332.78916002, 60022.35759088, 22704.05251298, ...,
       47107.41755234, 64280.5088809 , 36234.09781938])

In [15]:
X_train.head(2)

,Brand,Variant,Series,Year,Kilometers,Type,Gearbox,Fuel,Status,CC,Color,Seating Capacity
7720,57,1497,58,23,108607,11,1,3,2,1984,16,4
6627,51,1904,1557,33,9,52,1,5,1,1395,166,5

In [16]:
input_data_model = pd.DataFrame(
    [[57,1497,58,23,108607,11,1,3,2,1984,16,4]],
    columns=['Brand', 'Variant', 'Series',	'Year',	'Kilometers',	'Type',	'Gearbox',	'Fuel',	'Status',	'CC',	'Color',	'Seating Capacity'])

In [17]:
model.predict(input_data_model)

array([30611.02721994])

In [18]:
import pickle as pk

In [19]:
pk.dump(model,open('model.pkl','wb'))